[package]
name = "twitch_eventsub_structs"
version = "0.1.2"
edition = "2021"
authors = ["Owlkaline"]
resolver = "2"
license = "MIT"

[dependencies]
serde_json = "1.0.117"
serde = "1.0.117"
serde_derive = "1.0.117"
serde_with = "3.8.3"
